// <auto-generated />
namespace LoanManagement.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedComm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedComm));
        
        string IMigrationMetadata.Id
        {
            get { return "201402212349294_AddedComm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
