// <auto-generated />
namespace LoanManagement.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CollateralLoanInfo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollateralLoanInfo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201401042310278_CollateralLoanInfo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
